from parsers.base_classes import ParserList
from parsers.vk_parser import VKParser
from parsers.telegram_parser import TelegramParser

channels_names = {
    1: 'СНТО им. Н. Е. Жуковского',
    2: 'Молодежный Космический Центр',
    3: 'ART CLUB BMSTU',
    4: 'Камерный хор "Gaudeamus" МГТУ им. Баумана',
    5: 'Профсоюз студентов МГТУ им. Н.Э. Баумана',
    6: '24х36',
    7: 'VK | МГТУ им. Н.Э. Баумана',
    8: 'Центр карьеры МГТУ им. Н.Э. Баумана',
    9: 'Центр креативных индустрий',
    10: 'Студенческий спортивный клуб МГТУ им.Н.Э.Баумана',
    11: 'КАиС МГТУ им. Н.Э. Баумана',
    12: 'Театр-студия «Голос»',
    13: 'pmvoices | хор Perpetuum Mobile',
    14: 'Аrt-Club Production - организация концертов',
    15: 'LEGION | DANCE FAMILY',
    16: 'НЕАПОЛИТАНСКИЙ АНСАМБЛЬ ИМЕНИ МИСАИЛОВЫХ',
    17: 'Центр допобразования МГТУ им. Н.Э. Баумана',
    18: 'ПИШ МГТУ им. Н.Э. Баумана',
    19: 'Молодежный инженерный центр | МИЦ',
    20: 'Ernestovich',
    21: 'Центр молодёжной робототехники',
    22: 'BAUMAN HOCKEY',
    23: 'BAUMAN STREET',
    24: 'BMSTU Ultras - Бауманский фан-движ',
    25: 'Izmaylovo Football League of Bauman University',
    26: 'Bauman Active Sports | BAS',
    27: 'Bauman Racing Team',
    28: 'Волейбольный клуб МГТУ им. Н.Э. Баумана',
    29: 'БауманКан',
    30: 'WWbmstu -Клуб водного туризма ТК МГТУ им.Баумана',
    31: 'Студенческий совет МГТУ им. Н.Э. Баумана',
    32: 'B2B: Бауманцы для Бауманцев',
    33: 'Профсоюз работников МГТУ им. Н.Э. Баумана',
    34: 'Студенческий совет НУК РЛМ',
    35: 'Telegram | МГТУ им. Н.Э. Баумана',
    36: 'Центр НТИ «Цифровое материаловедение» МГТУ им. Н.Э. Баумана',
}

full_parser_list = ParserList(
    VKParser(1, domain='bmstu_snto'),
    VKParser(2, domain='ysc_bmstu_sm'),
    VKParser(3, domain='artclub.bmstu'),
    VKParser(4, domain='club5248660'),
    VKParser(5, domain='profkom_bmstu'),
    VKParser(6, domain='analog24x36'),
    VKParser(7, domain='bmstu1830'),
    VKParser(8, domain='bmstu_career'),
    VKParser(9, domain='creative_center_bmstu'),
    VKParser(10, domain='ssc_bmstu'),
    VKParser(11, domain='alp.bmstu'),
    VKParser(12, domain='theatregolos'),
    VKParser(13, domain='pmvoices'),
    VKParser(14, domain='art_club_production'),
    VKParser(15, domain='legionbmstu'),
    VKParser(16, domain='neapolmisailov'),
    VKParser(17, domain='do_bmstu_ru'),
    VKParser(18, domain='engineers2030bmstu'),
    VKParser(19, domain='mic.bmstu'),
    VKParser(20, domain='club224526757'),
    VKParser(21, domain='robotics_bmstu'),
    VKParser(22, domain='hc_bmstu'),
    VKParser(23, domain='bmstubasket'),
    VKParser(24, domain='bmstu_ultras'),
    VKParser(25, domain='ifl_bmstu'),
    VKParser(26, domain='bas.bmstu'),
    VKParser(27, domain='brt_fs'),
    VKParser(28, domain='vcbmstu'),
    VKParser(29, domain='baumankan'),
    VKParser(30, domain='wwbmstu'),
    TelegramParser(31, channel='studsovet_bmstu'),
    TelegramParser(32, channel='b2b_bmstu'),
    TelegramParser(33, channel='prof_bmstu'),
    TelegramParser(34, channel='student_rlm'),
    TelegramParser(35, channel='bmstu1830'),
    TelegramParser(36, channel='nti_bmstu'),
)
